from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


REQUIRED_COLUMNS = {"rank", "model_name", "annual_energy_park_mwh"}


def enrich_ranking_with_gaps(ranking_df: pd.DataFrame) -> pd.DataFrame:
    missing = REQUIRED_COLUMNS.difference(ranking_df.columns)
    if missing:
        raise ValueError(f"Missing required columns in ranking CSV: {sorted(missing)}")

    out = ranking_df.copy()
    out["rank"] = pd.to_numeric(out["rank"], errors="coerce")
    out["annual_energy_park_mwh"] = pd.to_numeric(out["annual_energy_park_mwh"], errors="coerce")
    out = out.dropna(subset=["rank", "annual_energy_park_mwh", "model_name"]).copy()
    if out.empty:
        raise ValueError("Ranking CSV has no valid rows after parsing")

    out = out.sort_values("rank", ascending=True, kind="mergesort").reset_index(drop=True)

    best_energy = float(out.loc[0, "annual_energy_park_mwh"])
    if best_energy <= 0:
        raise ValueError("Best annual energy must be > 0 to compute relative gaps")

    out["gap_mwh_from_best"] = best_energy - out["annual_energy_park_mwh"]
    out["gap_pct_from_best"] = (out["gap_mwh_from_best"] / best_energy) * 100.0
    out["delta_mwh_vs_prev_rank"] = (
        out["annual_energy_park_mwh"].shift(1) - out["annual_energy_park_mwh"]
    ).fillna(0.0)
    return out


def plot_ranking_and_gaps(
    ranking_df: pd.DataFrame,
    output_png: Path,
    title: str,
) -> None:
    output_png.parent.mkdir(parents=True, exist_ok=True)

    best_model = str(ranking_df.loc[0, "model_name"])
    chart_df = ranking_df.sort_values("annual_energy_park_mwh", ascending=True).reset_index(drop=True)
    colors = ["#f28e2b" if model == best_model else "#4e79a7" for model in chart_df["model_name"]]

    fig = plt.figure(figsize=(14, 10), constrained_layout=True)
    grid = fig.add_gridspec(2, 1, height_ratios=[3, 2], hspace=0.28)

    ax1 = fig.add_subplot(grid[0, 0])
    ax1.barh(chart_df["model_name"], chart_df["annual_energy_park_mwh"], color=colors)
    ax1.set_title(title, fontsize=14)
    ax1.set_xlabel("Annual energy for standard park (MWh)")
    ax1.set_ylabel("Turbine model")
    ax1.grid(axis="x", linestyle="--", alpha=0.35)

    energy_max = float(chart_df["annual_energy_park_mwh"].max())
    x_pad = energy_max * 0.01
    for _, row in chart_df.iterrows():
        ax1.text(
            float(row["annual_energy_park_mwh"]) + x_pad,
            row["model_name"],
            f"{float(row['annual_energy_park_mwh']):,.0f}",
            va="center",
            fontsize=8,
        )

    ax2 = fig.add_subplot(grid[1, 0])
    ax2.bar(
        ranking_df["rank"].astype(int),
        ranking_df["gap_pct_from_best"],
        color="#e15759",
        alpha=0.75,
    )
    ax2.plot(
        ranking_df["rank"].astype(int),
        ranking_df["gap_pct_from_best"],
        color="#b23a48",
        marker="o",
        linewidth=1.2,
    )
    ax2.set_xlabel("Rank")
    ax2.set_ylabel("Gap from best (%)")
    ax2.set_title("Relative performance gap vs best model")
    ax2.grid(axis="y", linestyle="--", alpha=0.35)
    ax2.set_xticks(ranking_df["rank"].astype(int).to_list())

    for _, row in ranking_df.iterrows():
        x = int(row["rank"])
        y = float(row["gap_pct_from_best"])
        ax2.text(x, y + 0.15, f"{y:.2f}%", ha="center", va="bottom", fontsize=8)

    plt.savefig(output_png, dpi=200)
    plt.close(fig)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Visualize turbine ranking and performance gaps from a turbine_ranking.csv file."
        )
    )
    parser.add_argument(
        "--ranking-csv",
        type=Path,
        required=True,
        help="Path to turbine_ranking.csv generated by select_turbine_weibull",
    )
    parser.add_argument(
        "--output-png",
        type=Path,
        default=None,
        help="Output PNG path (default: <ranking-dir>/turbine_ranking_performance_gaps.png)",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=None,
        help="Output enriched CSV path (default: <ranking-dir>/turbine_ranking_with_gaps.csv)",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="Turbine Ranking and Performance Gaps",
        help="Plot title",
    )
    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    ranking_csv = Path(args.ranking_csv)
    if not ranking_csv.exists():
        raise FileNotFoundError(f"Ranking CSV not found: {ranking_csv}")

    output_png = (
        Path(args.output_png)
        if args.output_png is not None
        else ranking_csv.parent / "turbine_ranking_performance_gaps.png"
    )
    output_csv = (
        Path(args.output_csv)
        if args.output_csv is not None
        else ranking_csv.parent / "turbine_ranking_with_gaps.csv"
    )

    ranking_df = pd.read_csv(ranking_csv)
    enriched_df = enrich_ranking_with_gaps(ranking_df)
    plot_ranking_and_gaps(
        ranking_df=enriched_df,
        output_png=output_png,
        title=str(args.title),
    )
    enriched_df.to_csv(output_csv, index=False, encoding="utf-8")

    best = enriched_df.iloc[0]
    print("----- Turbine Ranking Visualization -----")
    print(f"Input ranking CSV: {ranking_csv}")
    print(f"Output PNG: {output_png}")
    print(f"Output enriched CSV: {output_csv}")
    print(
        "Best model: "
        f"{best['model_name']} "
        f"(annual_energy_park_mwh={float(best['annual_energy_park_mwh']):.2f})"
    )


if __name__ == "__main__":
    main()
